name: Build OBS Virtual Webcam

on:
  pull_request:
  push:
    branches:
    - master
    - pkg-build
    tags:
    - "v*"

jobs:
  build:
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.13
      obs-studio-ref: 25.0.8
    runs-on: macos-latest

    steps:
    - name: Checkout obs-mac-virtualcam
      uses: actions/checkout@v2
      with:
        path: obs-mac-virtualcam

    - name: Cache OBS Build
      id: cache-obs-build
      uses: actions/cache@v1
      with:
        path: obs-studio
        key: obs-studio-${{ env.obs-studio-ref }}-macOS${{ env.MACOSX_DEPLOYMENT_TARGET }}

    - name: Install OBS deps
      if: steps.cache-obs-build.outputs.cache-hit != 'true'
      run: |
        brew bundle -v --file=obs-mac-virtualcam/Brewfile
    - name: Checkout OBS
      if: steps.cache-obs-build.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: obsproject/obs-studio
        path: obs-studio
        submodules: recursive
        ref: ${{ env.obs-studio-ref }}

    - name: Build OBS
      if: steps.cache-obs-build.outputs.cache-hit != 'true'
      run: |
        mkdir -p obs-studio/build
        cd obs-studio/build
        export QTDIR=$(brew --prefix qt5)
        cmake ..
        make -j
    - name: Install obs-mac-virtualcam deps
      run: |
        brew install cmake qt5
    - name: Build the plugin
      run: |
        mkdir obs-mac-virtualcam/build
        cd obs-mac-virtualcam/build
        cmake -DLIBOBS_INCLUDE_DIR:STRING=$GITHUB_WORKSPACE/obs-studio/libobs \
          -DLIBOBS_LIB:STRING=$GITHUB_WORKSPACE/obs-studio/build/libobs/libobs.dylib \
          -DOBS_FRONTEND_LIB:STRING=$GITHUB_WORKSPACE/obs-studio/build/UI/obs-frontend-api/libobs-frontend-api.dylib \
          -DQTDIR:STRING=$(brew --prefix qt5) ..
        make -j
